### ISSUE TITLE
[Feature] Return geojson dict after geo-inference call.

### ISSUE THREAD

**Issue by mpelchat04** [NRCan/geo-inference#30]
Integration of geo-inference with other tools would be facilitated if the results from the inference call was returned by the function.  https://github.com/NRCan/geo-inference/blob/main/geo_inference/geo_inference.py#L130  

Current behavior  
geo_inference returns the written mask name.    

Suggested behavior    
if `mask_to_vec == False`, returns mask name.  
if `mask_to_vec == True`, returns mask name + the geojson.

**Comment by valhassan** [comment]
In a scenario where we would like integration with the outputs from geo-inference; I would say a simple one-liner to read the geojson and return the geojson dict is a cleaner approach. I think this is doable in any language.

**Comment by mpelchat04** [comment]
Non-issue. Will not be addressed.
